version : '3'
services:
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hex_test
    ports:
      - "3307:3306"
    volumes:
      - "./testdb:/docker-entrypoint-initdb.d"
      - "v-hex-mysql-docker:/var/lib/mysql"

  grpc:
    build: .
    environment: 
      DB_DRIVER: "mysql"
      DS_NAME: "root:root@tcp(db:3307)/hex_test"
    depends_on:
      - db
    command: ["go", "test", "-v", "./..."]
volumes: 
  v-hex-mysql-docker: